parameters:
    locale: 'en'
    base_url: '%env(resolve:BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener

    App\Controller\ExceptionController:
        arguments:
            $exceptionCodes: '@fos_rest.exception.codes_map'
            
    App\Controller\RegistrationController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'
            $userManager: '@fos_user.user_manager'
            $dispatcher: '@event_dispatcher'
            
    event.jwt_created_listener:
        class: App\Event\Listener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }